Feat/student db
Just-a-NoobieDev/smart-bottle-bin pull request #14
Opened 2023-09-09 11:13 UTC by NoahMarkDelaPena

Front-end only Student Dashboard's Dashboard (Responsive)

2023-09-09 12:07 UTC, Just-a-NoobieDev requested changes
Just check the code, may for changes lang ako tas request before ko approve.

2023-09-09 12:07 UTC, Just-a-NoobieDev commented on components/ui/Sidebar.jsx
> +      <div className="bg-[#5B801A] h-[95%] w-[254px] rounded-b-full flex flex-col items-center py-10">
@NoahMarkDelaPena  Paalis nung changes na to 300px na talaga natin yung width kase may breakpoint na sabog kapag 254 lang

2023-09-09 12:07 UTC, Just-a-NoobieDev commented on components/ui/Sidebar.jsx
> +              className={`flex items-center justify-start w-full p-3 cursor-pointer hover:bg-[#91B552] ${
pa revert nalang din nito ayusin ko nalang sa branch ko ng sidebar yan

2023-09-09 12:07 UTC, Just-a-NoobieDev commented on app/(student)/dashboard/page.jsx
> +        <div className="w-[326px] h-[214px] bg-white shadow-cards rounded-[20px] p-4 md:w-[678px] md:h-[256px] md:p-7 xl:w-[425px] 2xl:w-[575px]">
Dito sa recent transaction  tas recent point allocation kaya ba gawan to ng isang component nalang kase same style nagkaiba lang naman ng names e tas gagamitin din to sa admin diba mas better nalang na naka component nalang to para reusable nlang tas para mas madali maintain @NoahMarkDelaPena

2023-09-09 12:07 UTC, Just-a-NoobieDev commented on app/(student)/dashboard/page.jsx
> +          <div className="w-[290px] h-[180px] bg-[#707070] md:w-[590px] md:h-[280px]"></div>
Tas abang mo na dito yung sa chart @NoahMarkDelaPena browse ka na nung sa chart.js para dire diretso na sa backend

2023-09-09 13:59 UTC, NoahMarkDelaPena commented on components/ui/Sidebar.jsx
> +      <div className="bg-[#5B801A] h-[95%] w-[254px] rounded-b-full flex flex-col items-center py-10">
Done po ito

2023-09-09 13:59 UTC, NoahMarkDelaPena commented on components/ui/Sidebar.jsx
> +              className={`flex items-center justify-start w-full p-3 cursor-pointer hover:bg-[#91B552] ${
Done po ito

2023-09-09 14:15 UTC, NoahMarkDelaPena commented on app/(student)/dashboard/page.jsx
> +        <div className="w-[326px] h-[214px] bg-white shadow-cards rounded-[20px] p-4 md:w-[678px] md:h-[256px] md:p-7 xl:w-[425px] 2xl:w-[575px]">
![image](https://github.com/Just-a-NoobieDev/smart-bottle-bin/assets/141199156/3419f427-eb13-4353-8352-132122452367)

2023-09-09 14:45 UTC, Just-a-NoobieDev commented on app/(student)/dashboard/page.jsx
> +        <div className="w-[326px] h-[214px] bg-white shadow-cards rounded-[20px] p-4 md:w-[678px] md:h-[256px] md:p-7 xl:w-[425px] 2xl:w-[575px]">
oks for now may babaguhin nalang kapag nilagyan na backend

2023-09-10 13:12 UTC, NoahMarkDelaPena commented on app/(student)/dashboard/page.jsx
> +          <div className="w-[290px] h-[180px] bg-[#707070] md:w-[590px] md:h-[280px]"></div>
done po ito

2023-09-10 13:38 UTC, closed without merging