Feat/student pointallocation
Just-a-NoobieDev/smart-bottle-bin pull request #16
Opened 2023-09-09 12:02 UTC by gioyap

I completed the responsive UI design of student db of point allocation history, it contains dropdown of sort button, filters have a modal and view details button have a modal also with blurred bg. I also fixed the error from eslint

2023-09-09 12:50 UTC, Just-a-NoobieDev requested changes
Pa resolve all review @gioyap before merge thank you

2023-09-09 12:50 UTC, Just-a-NoobieDev commented on app/(student)/point-allocations/page.jsx
> +  const [isOpen, setIsOpen] = useState(initialIsOpenState);
pwede mo naman na dito ipasa sa useState yung false mismo e haha pinahaba mo pa  code
```suggestion
  const [isOpen, setIsOpen] = useState(false);
```

2023-09-09 12:50 UTC, Just-a-NoobieDev commented on app/(student)/point-allocations/page.jsx
> +    });
pwede to pasimplehin like
```suggestion
  const toggleTransaction = (index) => {
    setIsOpen((prev) => !prev);
```

2023-09-09 12:50 UTC, Just-a-NoobieDev commented on app/(student)/point-allocations/page.jsx
> +  const [isSort, setIsSort] = useState(false);
@gioyap Palagay ng mga comment para kanino mga tong useState na to

2023-09-09 12:50 UTC, Just-a-NoobieDev commented on app/(student)/point-allocations/page.jsx
> +        </div>
@gioyap gawan mo ito sarili nga component kase reusable component to para mas madali maintain code nato

2023-09-09 12:50 UTC, Just-a-NoobieDev commented on app/(student)/point-allocations/page.jsx
> +      }
palagyan comment para saan tong block of code na to

2023-09-09 12:50 UTC, Just-a-NoobieDev commented on app/(student)/point-allocations/page.jsx
> +      )}
same palagyan lang comment

2023-09-09 12:50 UTC, Just-a-NoobieDev commented on app/(student)/point-allocations/page.jsx
> +          </div>
gawan mo din to ng component para maging reusable sa ibang page

2023-09-09 14:50 UTC, gioyap commented on app/(student)/point-allocations/page.jsx
> +    });
pre sinunod ko yan kaso biglang hindi nag function yung threedots sa table

2023-09-09 14:52 UTC, gioyap commented on app/(student)/point-allocations/page.jsx
> +  const [isOpen, setIsOpen] = useState(initialIsOpenState);
same dito pre, somehow magkacorrelate sila ng line 19 to 24 haha. may lumalabas na error kapag pinipindot ko yung threedots.

2023-09-10 11:09 UTC, Just-a-NoobieDev commented on app/(student)/point-allocations/page.jsx
> +    });
ano error

2023-09-10 11:10 UTC, Just-a-NoobieDev commented on app/(student)/point-allocations/page.jsx
> +  const [isOpen, setIsOpen] = useState(initialIsOpenState);
ano nalabas na error?

2023-09-10 13:47 UTC, Just-a-NoobieDev approved these changes

2023-09-10 13:47 UTC, merged